/**
 * Copyright 2013 Joan Zapata
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * It uses FontAwesome font, licensed under OFL 1.1, which is compatible
 * with this library's license.
 *
 *     http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt
 */
package com.joanzapata.android.iconify;

import android.content.Context;
import android.graphics.Typeface;
import android.text.Spanned;
import android.widget.TextView;

import java.io.IOException;

import static android.text.Html.fromHtml;
import static android.text.Html.toHtml;
import static com.joanzapata.android.iconify.Utils.replaceIcons;
import static com.joanzapata.android.iconify.Utils.resourceToFile;
import static java.lang.String.valueOf;

public final class Iconify {

    private static final String TTF_FILE = "fontawesome-webfont-4.4.0.ttf";

    public static final String TAG = Iconify.class.getSimpleName();

    private static Typeface typeface = null;

    private Iconify() {
        // Prevent instantiation
    }

    /**
     * Transform the given TextViews replacing {icon_xxx} texts with icons.
     */
    public static final void addIcons(TextView... textViews) {
        for (TextView textView : textViews) {
            textView.setTypeface(getTypeface(textView.getContext()));
            textView.setText(compute(textView.getText()));
        }
    }

    public static CharSequence compute(CharSequence charSequence) {
        if (charSequence instanceof Spanned) {
            String text = toHtml((Spanned) charSequence);
            return fromHtml(replaceIcons(new StringBuilder((text))).toString());
        }
        String text = charSequence.toString();
        return replaceIcons(new StringBuilder(text));
    }

    public static final void setIcon(TextView textView, IconValue value) {
        textView.setTypeface(getTypeface(textView.getContext()));
        textView.setText(valueOf(value.character));
    }

    /**
     * The typeface that contains FontAwesome icons.
     *
     * @return the typeface, or null if something goes wrong.
     */
    public static final Typeface getTypeface(Context context) {
        if (typeface == null) {
            try {
                typeface = Typeface.createFromFile(resourceToFile(context, TTF_FILE));
            } catch (IOException e) {
                return null;
            }
        }
        return typeface;
    }

    public static enum IconValue {

        fa_500px('\uf26e', false),
        fa_adjust('\uf042', false),
        fa_adn('\uf170'),
        fa_align_center('\uf037'),
        fa_align_justify('\uf039'),
        fa_align_left('\uf036'),
        fa_align_right('\uf038'),
        fa_amazon('\uf270', false),
        fa_ambulance('\uf0f9'),
        fa_anchor('\uf13d'),
        fa_android('\uf17b'),
        fa_angellist('\uf209', false),
        fa_angle_double_down('\uf103'),
        fa_angle_double_left('\uf100'),
        fa_angle_double_right('\uf101'),
        fa_angle_double_up('\uf102'),
        fa_angle_down('\uf107'),
        fa_angle_left('\uf104'),
        fa_angle_right('\uf105'),
        fa_angle_up('\uf106'),
        fa_apple('\uf179', false),
        fa_archive('\uf187'),
        fa_area_chart('\uf1fe'),
        fa_arrow_circle_down('\uf0ab'),
        fa_arrow_circle_left('\uf0a8'),
        fa_arrow_circle_o_down('\uf01a'),
        fa_arrow_circle_o_left('\uf190'),
        fa_arrow_circle_o_right('\uf18e'),
        fa_arrow_circle_o_up('\uf01b'),
        fa_arrow_circle_right('\uf0a9'),
        fa_arrow_circle_up('\uf0aa'),
        fa_arrow_down('\uf063'),
        fa_arrow_left('\uf060'),
        fa_arrow_right('\uf061'),
        fa_arrow_up('\uf062'),
        fa_arrows('\uf047'),
        fa_arrows_alt('\uf0b2'),
        fa_arrows_h('\uf07e'),
        fa_arrows_v('\uf07d'),
        fa_asterisk('\uf069'),
        fa_at('\uf1fa', false),
        fa_automobile('\uf1b9'),
        fa_backward('\uf04a'),
        fa_balance_scale('\uf24e'),
        fa_ban('\uf05e'),
        fa_bank('\uf19c'),
        fa_bar_chart('\uf080'),
        fa_bar_chart_o('\uf080'),
        fa_barcode('\uf02a'),
        fa_bars('\uf0c9'),
        fa_battery_0('\uf244', false),
        fa_battery_1('\uf243', false),
        fa_battery_2('\uf242', false),
        fa_battery_3('\uf241', false),
        fa_battery_4('\uf240', false),
        fa_battery_empty('\uf244', false),
        fa_battery_full('\uf240', false),
        fa_battery_half('\uf242', false),
        fa_battery_quarter('\uf243', false),
        fa_battery_three_quarters('\uf241', false),
        fa_bed('\uf236'),
        fa_beer('\uf0fc'),
        fa_behance('\uf1b4', false),
        fa_behance_square('\uf1b5', false),
        fa_bell('\uf0f3'),
        fa_bell_o('\uf0a2'),
        fa_bell_slash('\uf1f6', false),
        fa_bell_slash_o('\uf1f7', false),
        fa_bicycle('\uf206'),
        fa_binoculars('\uf1e5'),
        fa_birthday_cake('\uf1fd'),
        fa_bitbucket('\uf171'),
        fa_bitbucket_square('\uf172'),
        fa_bitcoin('\uf15a', false),
        fa_black_tie('\uf27e'),
        fa_bold('\uf032', false),
        fa_bolt('\uf0e7'),
        fa_bomb('\uf1e2'),
        fa_book('\uf02d'),
        fa_bookmark('\uf02e'),
        fa_bookmark_o('\uf097'),
        fa_briefcase('\uf0b1'),
        fa_btc('\uf15a', false),
        fa_bug('\uf188'),
        fa_building('\uf1ad'),
        fa_building_o('\uf0f7'),
        fa_bullhorn('\uf0a1'),
        fa_bullseye('\uf140'),
        fa_bus('\uf207'),
        fa_buysellads('\uf20d', false),
        fa_cab('\uf1ba'),
        fa_calculator('\uf1ec'),
        fa_calendar('\uf073'),
        fa_calendar_check_o('\uf274'),
        fa_calendar_minus_o('\uf272'),
        fa_calendar_o('\uf133'),
        fa_calendar_plus_o('\uf271'),
        fa_calendar_times_o('\uf273'),
        fa_camera('\uf030'),
        fa_camera_retro('\uf083'),
        fa_car('\uf1b9'),
        fa_caret_down('\uf0d7'),
        fa_caret_left('\uf0d9'),
        fa_caret_right('\uf0da'),
        fa_caret_square_o_down('\uf150'),
        fa_caret_square_o_left('\uf191'),
        fa_caret_square_o_right('\uf152'),
        fa_caret_square_o_up('\uf151'),
        fa_caret_up('\uf0d8'),
        fa_cart_arrow_down('\uf218'),
        fa_cart_plus('\uf217'),
        fa_cc('\uf20a', false),
        fa_cc_amex('\uf1f3', false),
        fa_cc_diners_club('\uf24c', false),
        fa_cc_discover('\uf1f2', false),
        fa_cc_jcb('\uf24b', false),
        fa_cc_mastercard('\uf1f1', false),
        fa_cc_paypal('\uf1f4', false),
        fa_cc_stripe('\uf1f5', false),
        fa_cc_visa('\uf1f0', false),
        fa_certificate('\uf0a3'),
        fa_chain('\uf0c1'),
        fa_chain_broken('\uf127'),
        fa_check('\uf00c', false),
        fa_check_circle('\uf058', false),
        fa_check_circle_o('\uf05d', false),
        fa_check_square('\uf14a', false),
        fa_check_square_o('\uf046', false),
        fa_chevron_circle_down('\uf13a'),
        fa_chevron_circle_left('\uf137'),
        fa_chevron_circle_right('\uf138'),
        fa_chevron_circle_up('\uf139'),
        fa_chevron_down('\uf078'),
        fa_chevron_left('\uf053'),
        fa_chevron_right('\uf054'),
        fa_chevron_up('\uf077'),
        fa_child('\uf1ae'),
        fa_chrome('\uf268', false),
        fa_circle('\uf111'),
        fa_circle_o('\uf10c'),
        fa_circle_o_notch('\uf1ce'),
        fa_circle_thin('\uf1db'),
        fa_clipboard('\uf0ea'),
        fa_clock_o('\uf017'),
        fa_clone('\uf24d'),
        fa_close('\uf00d'),
        fa_cloud('\uf0c2'),
        fa_cloud_download('\uf0ed'),
        fa_cloud_upload('\uf0ee'),
        fa_cny('\uf157'),
        fa_code('\uf121', false),
        fa_code_fork('\uf126'),
        fa_codepen('\uf1cb'),
        fa_coffee('\uf0f4'),
        fa_cog('\uf013'),
        fa_cogs('\uf085', false),
        fa_columns('\uf0db'),
        fa_comment('\uf075', false),
        fa_comment_o('\uf0e5', false),
        fa_commenting('\uf27a', false),
        fa_commenting_o('\uf27b', false),
        fa_comments('\uf086', false),
        fa_comments_o('\uf0e6', false),
        fa_compass('\uf14e', false),
        fa_compress('\uf066'),
        fa_connectdevelop('\uf20e', false),
        fa_contao('\uf26d', false),
        fa_copy('\uf0c5', false),
        fa_copyright('\uf1f9', false),
        fa_creative_commons('\uf25e', false),
        fa_credit_card('\uf09d', false),
        fa_crop('\uf125'),
        fa_crosshairs('\uf05b'),
        fa_css3('\uf13c', false),
        fa_cube('\uf1b2'),
        fa_cubes('\uf1b3'),
        fa_cut('\uf0c4'),
        fa_cutlery('\uf0f5'),
        fa_dashboard('\uf0e4'),
        fa_dashcube('\uf210', false),
        fa_database('\uf1c0'),
        fa_dedent('\uf03b'),
        fa_delicious('\uf1a5'),
        fa_desktop('\uf108'),
        fa_deviantart('\uf1bd', false),
        fa_diamond('\uf219'),
        fa_digg('\uf1a6', false),
        fa_dollar('\uf155', false),
        fa_dot_circle_o('\uf192'),
        fa_download('\uf019', false),
        fa_dribbble('\uf17d', false),
        fa_dropbox('\uf16b', false),
        fa_drupal('\uf1a9', false),
        fa_edit('\uf044', false),
        fa_eject('\uf052'),
        fa_ellipsis_h('\uf141'),
        fa_ellipsis_v('\uf142'),
        fa_empire('\uf1d1'),
        fa_envelope('\uf0e0'),
        fa_envelope_o('\uf003'),
        fa_envelope_square('\uf199'),
        fa_eraser('\uf12d'),
        fa_eur('\uf153', false),
        fa_euro('\uf153', false),
        fa_exchange('\uf0ec'),
        fa_exclamation('\uf12a'),
        fa_exclamation_circle('\uf06a'),
        fa_exclamation_triangle('\uf071'),
        fa_expand('\uf065'),
        fa_expeditedssl('\uf23e'),
        fa_external_link('\uf08e', false),
        fa_external_link_square('\uf14c', false),
        fa_eye('\uf06e'),
        fa_eye_slash('\uf070', false),
        fa_eyedropper('\uf1fb'),
        fa_facebook('\uf09a', false),
        fa_facebook_f('\uf09a', false),
        fa_facebook_official('\uf230', false),
        fa_facebook_square('\uf082', false),
        fa_fast_backward('\uf049'),
        fa_fast_forward('\uf050'),
        fa_fax('\uf1ac'),
        fa_feed('\uf09e', false),
        fa_female('\uf182'),
        fa_fighter_jet('\uf0fb'),
        fa_file('\uf15b', false),
        fa_file_archive_o('\uf1c6', false),
        fa_file_audio_o('\uf1c7', false),
        fa_file_code_o('\uf1c9', false),
        fa_file_excel_o('\uf1c3', false),
        fa_file_image_o('\uf1c5', false),
        fa_file_movie_o('\uf1c8', false),
        fa_file_o('\uf016', false),
        fa_file_pdf_o('\uf1c1', false),
        fa_file_photo_o('\uf1c5', false),
        fa_file_picture_o('\uf1c5', false),
        fa_file_powerpoint_o('\uf1c4', false),
        fa_file_sound_o('\uf1c7', false),
        fa_file_text('\uf15c', false),
        fa_file_text_o('\uf0f6', false),
        fa_file_video_o('\uf1c8', false),
        fa_file_word_o('\uf1c2', false),
        fa_file_zip_o('\uf1c6', false),
        fa_files_o('\uf0c5', false),
        fa_film('\uf008'),
        fa_filter('\uf0b0'),
        fa_fire('\uf06d'),
        fa_fire_extinguisher('\uf134'),
        fa_firefox('\uf269', false),
        fa_flag('\uf024', false),
        fa_flag_checkered('\uf11e', false),
        fa_flag_o('\uf11d', false),
        fa_flash('\uf0e7', false),
        fa_flask('\uf0c3'),
        fa_flickr('\uf16e', false),
        fa_floppy_o('\uf0c7', false),
        fa_folder('\uf07b', false),
        fa_folder_o('\uf114', false),
        fa_folder_open('\uf07c', false),
        fa_folder_open_o('\uf115', false),
        fa_font('\uf031', false),
        fa_fonticons('\uf280', false),
        fa_forumbee('\uf211', false),
        fa_forward('\uf04e'),
        fa_foursquare('\uf180', false),
        fa_frown_o('\uf119', false),
        fa_futbol_o('\uf1e3'),
        fa_gamepad('\uf11b', false),
        fa_gavel('\uf0e3', false),
        fa_gbp('\uf154', false),
        fa_ge('\uf1d1'),
        fa_gear('\uf013'),
        fa_gears('\uf085'),
        fa_genderless('\uf22d'),
        fa_get_pocket('\uf265', false),
        fa_gg('\uf260', false),
        fa_gg_circle('\uf261'),
        fa_gift('\uf06b'),
        fa_git('\uf1d3', false),
        fa_git_square('\uf1d2', false),
        fa_github('\uf09b', false),
        fa_github_alt('\uf113', false),
        fa_github_square('\uf092', false),
        fa_gittip('\uf184'),
        fa_glass('\uf000'),
        fa_globe('\uf0ac', false),
        fa_google('\uf1a0', false),
        fa_google_plus('\uf0d5', false),
        fa_google_plus_square('\uf0d4', false),
        fa_google_wallet('\uf1ee', false),
        fa_graduation_cap('\uf19d', false),
        fa_gratipay('\uf184'),
        fa_group('\uf0c0'),
        fa_h_square('\uf0fd'),
        fa_hacker_news('\uf1d4'),
        fa_hand_grab_o('\uf255', false),
        fa_hand_lizard_o('\uf258', false),
        fa_hand_o_down('\uf0a7'),
        fa_hand_o_left('\uf0a5'),
        fa_hand_o_right('\uf0a4'),
        fa_hand_o_up('\uf0a6'),
        fa_hand_paper_o('\uf256'),
        fa_hand_peace_o('\uf25b'),
        fa_hand_pointer_o('\uf25a'),
        fa_hand_rock_o('\uf255'),
        fa_hand_scissors_o('\uf257'),
        fa_hand_spock_o('\uf259'),
        fa_hand_stop_o('\uf256'),
        fa_hdd_o('\uf0a0'),
        fa_header('\uf1dc'),
        fa_headphones('\uf025'),
        fa_heart('\uf004'),
        fa_heart_o('\uf08a'),
        fa_heartbeat('\uf21e', false),
        fa_history('\uf1da', false),
        fa_home('\uf015'),
        fa_hospital_o('\uf0f8'),
        fa_hotel('\uf236'),
        fa_hourglass('\uf254'),
        fa_hourglass_1('\uf251'),
        fa_hourglass_2('\uf252'),
        fa_hourglass_3('\uf253'),
        fa_hourglass_end('\uf253'),
        fa_hourglass_half('\uf252'),
        fa_hourglass_o('\uf250'),
        fa_hourglass_start('\uf251'),
        fa_houzz('\uf27c', false),
        fa_html5('\uf13b', false),
        fa_i_cursor('\uf246', false),
        fa_ils('\uf20b', false),
        fa_image('\uf03e'),
        fa_inbox('\uf01c'),
        fa_indent('\uf03c'),
        fa_industry('\uf275', false),
        fa_info('\uf129'),
        fa_info_circle('\uf05a'),
        fa_inr('\uf156', false),
        fa_instagram('\uf16d', false),
        fa_institution('\uf19c'),
        fa_internet_explorer('\uf26b', false),
        fa_intersex('\uf224', false),
        fa_ioxhost('\uf208', false),
        fa_italic('\uf033', false),
        fa_joomla('\uf1aa'),
        fa_jpy('\uf157'),
        fa_jsfiddle('\uf1cc', false),
        fa_key('\uf084', false),
        fa_keyboard_o('\uf11c', false),
        fa_krw('\uf159'),
        fa_language('\uf1ab', false),
        fa_laptop('\uf109'),
        fa_lastfm('\uf202', false),
        fa_lastfm_square('\uf203', false),
        fa_leaf('\uf06c', false),
        fa_leanpub('\uf212', false),
        fa_legal('\uf0e3', false),
        fa_lemon_o('\uf094', false),
        fa_level_down('\uf149'),
        fa_level_up('\uf148'),
        fa_life_bouy('\uf1cd'),
        fa_life_buoy('\uf1cd'),
        fa_life_ring('\uf1cd'),
        fa_life_saver('\uf1cd'),
        fa_lightbulb_o('\uf0eb'),
        fa_line_chart('\uf201', false),
        fa_link('\uf0c1'),
        fa_linkedin('\uf0e1', false),
        fa_linkedin_square('\uf08c', false),
        fa_linux('\uf17c', false),
        fa_list('\uf03a'),
        fa_list_alt('\uf022'),
        fa_list_ol('\uf0cb'),
        fa_list_ul('\uf0ca'),
        fa_location_arrow('\uf124'),
        fa_lock('\uf023'),
        fa_long_arrow_down('\uf175'),
        fa_long_arrow_left('\uf177'),
        fa_long_arrow_right('\uf178'),
        fa_long_arrow_up('\uf176'),
        fa_magic('\uf0d0'),
        fa_magnet('\uf076'),
        fa_mail_forward('\uf064'),
        fa_mail_reply('\uf112'),
        fa_mail_reply_all('\uf122'),
        fa_male('\uf183'),
        fa_map('\uf279'),
        fa_map_marker('\uf041'),
        fa_map_o('\uf278'),
        fa_map_pin('\uf276'),
        fa_map_signs('\uf277'),
        fa_mars('\uf222', false),
        fa_mars_double('\uf227', false),
        fa_mars_stroke('\uf229', false),
        fa_mars_stroke_h('\uf22b', false),
        fa_mars_stroke_v('\uf22a', false),
        fa_maxcdn('\uf136', false),
        fa_meanpath('\uf20c', false),
        fa_medium('\uf23a', false),
        fa_medkit('\uf0fa'),
        fa_meh_o('\uf11a'),
        fa_mercury('\uf223'),
        fa_microphone('\uf130'),
        fa_microphone_slash('\uf131'),
        fa_minus('\uf068'),
        fa_minus_circle('\uf056'),
        fa_minus_square('\uf146'),
        fa_minus_square_o('\uf147'),
        fa_mobile('\uf10b'),
        fa_mobile_phone('\uf10b'),
        fa_money('\uf0d6', false),
        fa_moon_o('\uf186', false),
        fa_mortar_board('\uf19d', false),
        fa_motorcycle('\uf21c'),
        fa_mouse_pointer('\uf245'),
        fa_music('\uf001', false),
        fa_navicon('\uf0c9'),
        fa_neuter('\uf22c'),
        fa_newspaper_o('\uf1ea'),
        fa_object_group('\uf247'),
        fa_object_ungroup('\uf248'),
        fa_odnoklassniki('\uf263'),
        fa_odnoklassniki_square('\uf264'),
        fa_opencart('\uf23d', false),
        fa_openid('\uf19b', false),
        fa_opera('\uf26a'),
        fa_optin_monster('\uf23c', false),
        fa_outdent('\uf03b'),
        fa_pagelines('\uf18c', false),
        fa_paint_brush('\uf1fc', false),
        fa_paper_plane('\uf1d8', false),
        fa_paper_plane_o('\uf1d9', false),
        fa_paperclip('\uf0c6', false),
        fa_paragraph('\uf1dd', false),
        fa_paste('\uf0ea', false),
        fa_pause('\uf04c'),
        fa_paw('\uf1b0', false),
        fa_paypal('\uf1ed', false),
        fa_pencil('\uf040', false),
        fa_pencil_square('\uf14b', false),
        fa_pencil_square_o('\uf044', false),
        fa_phone('\uf095', false),
        fa_phone_square('\uf098', false),
        fa_photo('\uf03e', false),
        fa_picture_o('\uf03e', false),
        fa_pie_chart('\uf200', false),
        fa_pied_piper('\uf1a7', false),
        fa_pied_piper_alt('\uf1a8', false),
        fa_pinterest('\uf0d2', false),
        fa_pinterest_p('\uf231', false),
        fa_pinterest_square('\uf0d3', false),
        fa_plane('\uf072', false),
        fa_play('\uf04b', false),
        fa_play_circle('\uf144', false),
        fa_play_circle_o('\uf01d', false),
        fa_plug('\uf1e6', false),
        fa_plus('\uf067'),
        fa_plus_circle('\uf055'),
        fa_plus_square('\uf0fe'),
        fa_plus_square_o('\uf196'),
        fa_power_off('\uf011'),
        fa_print('\uf02f'),
        fa_puzzle_piece('\uf12e'),
        fa_qq('\uf1d6', false),
        fa_qrcode('\uf029', false),
        fa_question('\uf128', false),
        fa_question_circle('\uf059', false),
        fa_quote_left('\uf10d'),
        fa_quote_right('\uf10e'),
        fa_ra('\uf1d0', false),
        fa_random('\uf074'),
        fa_rebel('\uf1d0', false),
        fa_recycle('\uf1b8'),
        fa_reddit('\uf1a1', false),
        fa_reddit_square('\uf1a2', false),
        fa_refresh('\uf021'),
        fa_registered('\uf25d', false),
        fa_remove('\uf00d'),
        fa_renren('\uf18b'),
        fa_reorder('\uf0c9'),
        fa_repeat('\uf01e', false),
        fa_reply('\uf112', false),
        fa_reply_all('\uf122', false),
        fa_retweet('\uf079', false),
        fa_rmb('\uf157'),
        fa_road('\uf018'),
        fa_rocket('\uf135', false),
        fa_rotate_left('\uf0e2'),
        fa_rotate_right('\uf01e'),
        fa_rouble('\uf158'),
        fa_rss('\uf09e', false),
        fa_rss_square('\uf143', false),
        fa_rub('\uf158', false),
        fa_ruble('\uf158', false),
        fa_rupee('\uf156', false),
        fa_safari('\uf267', false),
        fa_save('\uf0c7', false),
        fa_scissors('\uf0c4', false),
        fa_search('\uf002', false),
        fa_search_minus('\uf010', false),
        fa_search_plus('\uf00e', false),
        fa_sellsy('\uf213', false),
        fa_send('\uf1d8', false),
        fa_send_o('\uf1d9', false),
        fa_server('\uf233'),
        fa_share('\uf064', false),
        fa_share_alt('\uf1e0', false),
        fa_share_alt_square('\uf1e1', false),
        fa_share_square('\uf14d', false),
        fa_share_square_o('\uf045', false),
        fa_shekel('\uf20b', false),
        fa_sheqel('\uf20b', false),
        fa_shield('\uf132'),
        fa_ship('\uf21a'),
        fa_shirtsinbulk('\uf214'),
        fa_shopping_cart('\uf07a'),
        fa_sign_in('\uf090', false),
        fa_sign_out('\uf08b', false),
        fa_signal('\uf012', false),
        fa_simplybuilt('\uf215'),
        fa_sitemap('\uf0e8'),
        fa_skyatlas('\uf216', false),
        fa_skype('\uf17e', false),
        fa_slack('\uf198', false),
        fa_sliders('\uf1de'),
        fa_slideshare('\uf1e7'),
        fa_smile_o('\uf118'),
        fa_soccer_ball_o('\uf1e3'),
        fa_sort('\uf0dc'),
        fa_sort_alpha_asc('\uf15d', false),
        fa_sort_alpha_desc('\uf15e', false),
        fa_sort_amount_asc('\uf160', false),
        fa_sort_amount_desc('\uf161', false),
        fa_sort_asc('\uf0de'),
        fa_sort_desc('\uf0dd'),
        fa_sort_down('\uf0dd'),
        fa_sort_numeric_asc('\uf162', false),
        fa_sort_numeric_desc('\uf163', false),
        fa_sort_up('\uf0de'),
        fa_soundcloud('\uf1be', false),
        fa_space_shuttle('\uf197', false),
        fa_spinner('\uf110', false),
        fa_spoon('\uf1b1'),
        fa_spotify('\uf1bc', false),
        fa_square('\uf0c8'),
        fa_square_o('\uf096'),
        fa_stack_exchange('\uf18d', false),
        fa_stack_overflow('\uf16c', false),
        fa_star('\uf005'),
        fa_star_half('\uf089'),
        fa_star_half_empty('\uf123'),
        fa_star_half_full('\uf123'),
        fa_star_half_o('\uf123'),
        fa_star_o('\uf006'),
        fa_steam('\uf1b6', false),
        fa_steam_square('\uf1b7', false),
        fa_step_backward('\uf048'),
        fa_step_forward('\uf051'),
        fa_stethoscope('\uf0f1', false),
        fa_sticky_note('\uf249', false),
        fa_sticky_note_o('\uf24a', false),
        fa_stop('\uf04d'),
        fa_street_view('\uf21d'),
        fa_strikethrough('\uf0cc', false),
        fa_stumbleupon('\uf1a4', false),
        fa_stumbleupon_circle('\uf1a3', false),
        fa_subscript('\uf12c', false),
        fa_subway('\uf239'),
        fa_suitcase('\uf0f2'),
        fa_sun_o('\uf185'),
        fa_superscript('\uf12b', false),
        fa_support('\uf1cd'),
        fa_table('\uf0ce'),
        fa_tablet('\uf10a'),
        fa_tachometer('\uf0e4'),
        fa_tag('\uf02b', false),
        fa_tags('\uf02c', false),
        fa_tasks('\uf0ae'),
        fa_taxi('\uf1ba'),
        fa_television('\uf26c'),
        fa_tencent_weibo('\uf1d5', false),
        fa_terminal('\uf120', false),
        fa_text_height('\uf034'),
        fa_text_width('\uf035'),
        fa_th('\uf00a'),
        fa_th_large('\uf009'),
        fa_th_list('\uf00b'),
        fa_thumb_tack('\uf08d'),
        fa_thumbs_down('\uf165', false),
        fa_thumbs_o_down('\uf088', false),
        fa_thumbs_o_up('\uf087', false),
        fa_thumbs_up('\uf164', false),
        fa_ticket('\uf145', false),
        fa_times('\uf00d'),
        fa_times_circle('\uf057'),
        fa_times_circle_o('\uf05c'),
        fa_tint('\uf043'),
        fa_toggle_down('\uf150'),
        fa_toggle_left('\uf191'),
        fa_toggle_off('\uf204', false),
        fa_toggle_on('\uf205', false),
        fa_toggle_right('\uf152'),
        fa_toggle_up('\uf151'),
        fa_trademark('\uf25c', false),
        fa_train('\uf238'),
        fa_transgender('\uf224', false),
        fa_transgender_alt('\uf225', false),
        fa_trash('\uf1f8'),
        fa_trash_o('\uf014'),
        fa_tree('\uf1bb'),
        fa_trello('\uf181', false),
        fa_tripadvisor('\uf262', false),
        fa_trophy('\uf091'),
        fa_truck('\uf0d1'),
        fa_try('\uf195', false),
        fa_tty('\uf1e4'),
        fa_tumblr('\uf173', false),
        fa_tumblr_square('\uf174', false),
        fa_turkish_lira('\uf195', false),
        fa_tv('\uf26c'),
        fa_twitch('\uf1e8', false),
        fa_twitter('\uf099', false),
        fa_twitter_square('\uf081', false),
        fa_umbrella('\uf0e9', false),
        fa_underline('\uf0cd', false),
        fa_undo('\uf0e2'),
        fa_university('\uf19c'),
        fa_unlink('\uf127', false),
        fa_unlock('\uf09c', false),
        fa_unlock_alt('\uf13e', false),
        fa_unsorted('\uf0dc'),
        fa_upload('\uf093', false),
        fa_usd('\uf155', false),
        fa_user('\uf007'),
        fa_user_md('\uf0f0'),
        fa_user_plus('\uf234', false),
        fa_user_secret('\uf21b'),
        fa_user_times('\uf235', false),
        fa_users('\uf0c0'),
        fa_venus('\uf221'),
        fa_venus_double('\uf226'),
        fa_venus_mars('\uf228', false),
        fa_viacoin('\uf237'),
        fa_video_camera('\uf03d'),
        fa_vimeo('\uf27d', false),
        fa_vimeo_square('\uf194', false),
        fa_vine('\uf1ca', false),
        fa_vk('\uf189', false),
        fa_volume_down('\uf027', false),
        fa_volume_off('\uf026', false),
        fa_volume_up('\uf028', false),
        fa_warning('\uf071'),
        fa_wechat('\uf1d7', false),
        fa_weibo('\uf18a', false),
        fa_weixin('\uf1d7', false),
        fa_whatsapp('\uf232', false),
        fa_wheelchair('\uf193', false),
        fa_wifi('\uf1eb'),
        fa_wikipedia_w('\uf266', false),
        fa_windows('\uf17a', false),
        fa_won('\uf159'),
        fa_wordpress('\uf19a', false),
        fa_wrench('\uf0ad', false),
        fa_xing('\uf168', false),
        fa_xing_square('\uf169', false),
        fa_y_combinator('\uf23b'),
        fa_y_combinator_square('\uf1d4'),
        fa_yahoo('\uf19e'),
        fa_yc('\uf23b'),
        fa_yc_square('\uf1d4'),
        fa_yelp('\uf1e9', false),
        fa_yen('\uf157'),
        fa_youtube('\uf167', false),
        fa_youtube_play('\uf16a', false),
        fa_youtube_square('\uf166', false);

        char character;
        boolean supportsRtl;

        IconValue(char character) {
            this(character, true);
        }

        IconValue(char character, boolean supportsRtl) {
            this.character = character;
            this.supportsRtl = supportsRtl;
        }

        public String formattedName() {
            return "{" + name() + "}";
        }

        public char character() {
            return character;
        }

        public boolean supportsRtl() {
            return supportsRtl;
        }
    }
}
